%{
%}
disp("Program start");

close all;
ott.warning('once');
ott.change_warnings('off');

n_medium = 1.33;        % Water
n_particle = 1.59;      % Polystyrene
wavelength0 = 1064e-9;  % Vacuum wavelength
wavelength_medium = wavelength0 / n_medium;

view_range = 2e-6;

radius = 0.5*wavelength_medium;
p1_pos = [-2.0*radius; 0; 0];
p2_pos = [+2.0*radius; 0; 0];

%T-Matrix acting on simple sphere at origin
T = ott.Tmatrix.simple('sphere', radius, ...
   'wavelength0', wavelength0, ...
   'index_medium', n_medium, ...
   'index_particle', n_particle);

%Plane wave, X lin polarised, moving in +Z direction, centered at origin
%beam = ott.BscPlane(0, 0, ...
%    'polarisation', [ 1 0 ], ...
%    'index_medium', n_medium, ...
%    'wavelength0', wavelength0);
%Gaussian wave, X lin polarised, moving in Z direction, centered at origin
beam = ott.BscPmGauss('polarisation', [ 1 0 ], ...
    'index_medium', n_medium, ...
    'wavelength0', wavelength0, ...
    'translation_method', 'Default');

beam_scattered_p1_center = T * (translateXyz(beam, p1_pos));
beam_scattered_p2_center = T * (translateXyz(beam, p2_pos));
beam_scattered_p1 = translateXyz(beam_scattered_p1_center, -p1_pos);
beam_scattered_p2 = translateXyz(beam_scattered_p2_center, -p2_pos);

figure();
subplot(2,3,1);
beam.visualise('axis', 'z', ...
    'range', [1,1]*view_range ...
);
subplot(2,3,2);
beam_scattered_p1_center.visualise('axis', 'z', ...
    'mask', @(xyz) vecnorm(xyz) < radius, ...
    'range', [1,1]*view_range ...
);
subplot(2,3,3);
beam_scattered_p2_center.visualise('axis', 'z', ...
    'mask', @(xyz) vecnorm(xyz) < radius, ...
    'range', [1,1]*view_range ...
);
subplot(2,3,4);
beam.visualise('axis', 'z', ...
    'range', [1,1]*view_range ...
);
subplot(2,3,5);
beam_scattered_p1.visualise('axis', 'z', ...
    'mask', @(xyz) vecnorm(xyz) < radius, ...
    'range', [1,1]*view_range ...
);
subplot(2,3,6);
beam_scattered_p2.visualise('axis', 'z', ...
    'mask', @(xyz) vecnorm(xyz) < radius, ...
    'range', [1,1]*view_range ...
);

%%%%
%% DIFFICULTY NOW AS THE 'translateXyz()' SEEMS TO RE-CALCULATE THE T-MATRIX OR SOMETHING SIMILAR, NOT JUST MOVE THE PATTERN CREATED
%%%%


disp("Program end");